apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vyyrtn6kw-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:73b3d3b9d2335dd7aab6cb4b946f9b30cf56dd35@sha256:49b87ae1d20fb74add2dffd3bdc3996bfe6f91bbb7f870db5d0e05ebf3a93dd1
          name: container-image
