apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vyyrtn6kw-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vyyrtn6kw-dotnet-basic-gitops